### ISSUE TITLE
Update IntelliJ docs for multiple files in run config

### ISSUE THREAD

**Issue by sriv** [getgauge/docs.getgauge.io#20]
_From @mahendrakariya on June 9, 2016 11:11_

The delimiter for multiple spec files in run config has been changed from `,` to `||` due to https://github.com/getgauge/Intellij-Plugin/issues/101. This should be updated in the docs.

We also need to mention that this is a breaking change. Until v0.1.0 of IntelliJ plugin, the delimiter is `,`. Any higher version will have delimiter `||`.

_Copied from original issue: getgauge/documentation#51_

**Comment by BugDiver** [comment]
Docs are updated for multiple spec files execution.
