### ISSUE TITLE
More clarification for table parameter

### ISSUE THREAD

**Issue by sriv** [getgauge/docs.getgauge.io#21]
_From @mahendrakariya on June 23, 2016 13:46_

On the table params page http://getgauge.io/documentation/user/current/gauge_terminologies/parameters/table_parameters.html
- [x] At the top of the page, we start with `Table Parameters can be used in two ways`. Bullet should be removed from this line.
- [x] On this page, it's very difficult to find how a user can pass table as a param to step. I think someone new to Gauge will struggle a lot figuring this out. We should add more details about it.
- [x] Data driven execution should be mentioned at the end since it's a slightly advanced topic. The docs on this page should start with table param that can be passed to step.
- [x] There are no docs which says data table at spec level can also be passed from external sources. Should Data table driven scenarios be explained under `Param` section or `Execution` section? 

I also have a question. Will it be correct to call the table at the top of the spec as a `param`? We are not passing it as an arg to the step implementation. Personally, I feel it is not a param.

_Copied from original issue: getgauge/documentation#53_

**Comment by BugDiver** [comment]
The docs are updated.
