### ISSUE TITLE
The old document url is not getting redirected

### ISSUE THREAD

**Issue by sguptatw** [getgauge/docs.getgauge.io#27]
1. When I look for some info in Google like
`how to use Tags with specifications Gauge` the old document links are getting listed.

2. The old urls are not getting redirected properly eg: -getgauge.io/documentation/user/current/execution/tagged_execution.html should take us to the relevant page in the new documentation. It takes us to the main page in the new documentation.

getgauge.io/documentation/user/0.0.5/execution/tagged_execution.html is also taking us to the main page of the new documentation and not the relevant page.

**Comment by sriv** [comment]
Google search index is refreshed, and the old documentation links are not listed anymore under getgauge.io.

The old docs are available under getgauge.github.io (only as an archive, and can be outdated, have broken links etc).
