### ISSUE TITLE
The uninstallation path to be updated

### ISSUE THREAD

**Issue by sguptatw** [getgauge/docs.getgauge.io#29]
The uninstallation path mentioned in the docs is `rm -rf /usr/local/bin/gauge /usr/local/share/gauge /usr/local/share/gauge_screenshot ~/.gauge`

This should be updated with the latest folders as well

**Comment by BugDiver** [comment]
@sguptatw The path mentioned in docs are correct in `master`  and `latest` both the versions.
Could you verify it and close the issue?
