### ISSUE TITLE
No plugin creation documentation

### ISSUE THREAD

**Issue by boazberman** [getgauge/docs.getgauge.io#32]
Hey, I've gain some intrest writing a plugin myself, and after a search in the docs, I could'nt manage to find any documentation what so ever as to where should I start. I would love some guidance and even more if it will be added to the docs. Thanks!

**Comment by kashishm** [comment]
@boazberman you can access the plugin tech docs [here](http://getgauge.github.io/documentation/technical/current/types_of_plugins/). We are in the process of migrating the tech docs to Gauge wiki. So, we will be improving and adding more details to the wiki.

I have written a blog on [How to write a language runner](https://medium.com/@kashishmunjal/authoring-a-language-runner-for-gauge-1332b7bca8d8) and for reporting plugins, you can refer [HTML Report](https://github.com/getgauge/html-report) or [XML Report](https://github.com/getgauge/xml-report) plugin source code. I hope this helps.
