### ISSUE TITLE
When BeforeSpec is run for a specific spec file, it is running all the BeforeSpecs 

### ISSUE THREAD

**Issue by scsannalli** [getgauge/docs.getgauge.io#34]
When BeforeSpec is run for a specific spec file, it is running all the BeforeSpecs in c#
eg: I have 2 spec files (a.spec and b.spec), and have 2 different beforespec implementations (a.cs and b.cs). 
EveryTime I run a spec it is running beforeSpec of all spec files. 

How to avoid   this ?

**Comment by Apoorva-GA** [comment]
@scsannalli You can avoid this by tagging your BeforeSpec hook. This will ensure that BeforeSpec hook will run only on the specifications that have the required tag.
You can refer to our docs for details : https://docs.getgauge.io/using.html?highlight=tags%20beforespec#filtering-hooks-execution-based-on-tags

**Comment by BugDiver** [comment]
@scsannalli  If this is not resolved feel free to raise an issue [here](https://github.com/getgauge/gauge/issues/new).
I'm closing this issue.
