### ISSUE TITLE
Create a separate site for man page like description of commands

### ISSUE THREAD

**Issue by zabil** [getgauge/docs.getgauge.io#40]
When listing gauge usage from the cli we add the following link at the end

```
Complete documentation is available at https://docs.getgauge.io/.
```

However this lists the whole documentation and is a getting started guide.

Instead, use https://github.com/rtomayko/ronn to create a man page like listing for e.g. https://rtomayko.github.io/ronn/ronn.1.html of all the commands with examples for easy reading or printing.

As a plus bundle man pages for the cli so that shells like fish can auto complete and display in-line help.
Point documentation link on the cli to something like `manual.getgauge.io` and link to the main documentation from there.

Gain SEO points.

**Comment by sriv** [comment]
ronn looks old (last commit made in aug'13). For a ruby project, I am worried about the setup/dependencies.

Also, since we are on sphinx/rst stack, we can consider wiring up sphinx-build to out a manpage, using [`ManualPageBuilder`](http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.manpage.ManualPageBuilder)

**Comment by kashishm** [comment]
[Cobra](https://github.com/spf13/cobra) can generate man pages and markdown format usage also.
But it is very basic. Example: `man gauge`
```
NAME
       gauge -

SYNOPSIS
       gauge <command> [flags] [args]

DESCRIPTION
OPTIONS
       -d, --dir="."
           Set the working directory for the current command, accepts a path relative to current directory

       -h, --help[=false]
           help for gauge

       -l, --log-level="info"
           Set level of logging to debug, info, warning, error or critical

EXAMPLE
                gauge run specs/
                gauge run --parallel specs/

SEE ALSO
       gauge-add(1), gauge-config(1), gauge-daemon(1), gauge-docs(1), gauge-format(1), gauge-init(1),
       gauge-install(1), gauge-refactor(1), gauge-run(1), gauge-telemetry(1), gauge-uninstall(1), gauge-update(1),
       gauge-validate(1), gauge-version(1)
```

**Markdown output**

## gauge



### Synopsis




```
gauge <command> [flags] [args]
```

### Examples

```
  gauge run specs/
  gauge run --parallel specs/
```

### Options

```
  -d, --dir string         Set the working directory for the current command, accepts a path relative to current directory (default ".")
  -h, --help               help for gauge
  -l, --log-level string   Set level of logging to debug, info, warning, error or critical (default "info")
```

### SEE ALSO
* [gauge add](gauge_add.md)	 - Adds the specified non-language plugin to the current project
* [gauge config](gauge_config.md)	 - Change global configurations
* [gauge daemon](gauge_daemon.md)	 - Run as a daemon
* [gauge docs](gauge_docs.md)	 - Generate documentation using specified plugin
* [gauge format](gauge_format.md)	 - Formats the specified spec files
* [gauge init](gauge_init.md)	 - Initialize project structure in the current directory
* [gauge install](gauge_install.md)	 - Download and install plugin(s)
* [gauge refactor](gauge_refactor.md)	 - Refactor steps
* [gauge run](gauge_run.md)	 - Run specs
* [gauge telemetry](gauge_telemetry.md)	 - Configure options for sending anonymous usage statistics
* [gauge uninstall](gauge_uninstall.md)	 - Uninstalls a plugin
* [gauge update](gauge_update.md)	 - Updates a plugin
* [gauge validate](gauge_validate.md)	 - Check for validation and parse errors
* [gauge version](gauge_version.md)	 - Print Gauge and plugin versions

**Comment by BugDiver** [comment]
The online Gauge manual is available at https://manpage.getgauge.io.
Gauge Usages refers to online manpage instead of docs.
