### ISSUE TITLE
More details required in Run Configuration of "Gauge IntelliJ Idea Plugin Features"

### ISSUE THREAD

**Issue by sriv** [getgauge/docs.getgauge.io#8]
_From @navyakanu on September 22, 2015 6:2_

Under Section 11.1.1 Gauge IntelliJ Idea Plugin Features (6. Run Configurations) there are no details in the video for editing configurations with tags and parallel execution and the video displays only environment settings among the 4 points which is confusing

It would be more helpful if some options which are explained in detail for command line usage for gauge (like log customisation like setting up log-level in program arguments) if mentioned for IntelliJ IDE in section 11.6 Run Configuration

Kindly mention that concept should be written (rather called) in spec file (Section 2.5) like step which would be more easy to understand (this may not be self explanatory)

_Copied from original issue: getgauge/documentation#20_

**Comment by BugDiver** [comment]
Documentation for Run Configurations is updated.
